export default {
    connectionTestUrl: 'http://www.google.com',
    purchaseUrl: 'https://www.taskunifier.app/web/purchase',
    downloadUrl: 'https://www.taskunifier.app/web/app',
    versionUrl: 'https://www.taskunifier.app/api/versions/taskunifier-app/latest',
    color: '#008c4b',
    fadeColor: '#e3f2eb',
    lightColor: '#b8ccbf',
    disabledColor: '#cccccc',
    defaultObjectColor: '#ffffff',
    processRunningColor: '#20639b',
    processCompletedColor: '#3caea3',
    processErrorColor: '#ed553b',
    conditionTreeGroupAndColor: '#d1f7d9',
    conditionTreeGroupAndActiveColorColor: '#c2e2c9',
    conditionTreeGroupOrColor: '#e8ebf6',
    conditionTreeGroupOrActiveColor: '#d4d7e2',
    conditionTreeGroupNotColor: '#ffc8c5',
    conditionTreeGroupNotActiveColor: '#e3afac',
    archivedColor: '#5e666d',
    defaultTaskTemplateColor: '#ffd632',
    badgeColor: '#008c4b',
    calendarDateMode_startDate: '#32cd32',
    calendarDateMode_dueDate: '#1e90ff'
};