export default {
    itemSku: 'tu-cloud-pro-1y',
    connectionTestUrl: 'http://www.google.com',
    purchaseUrl: 'https://www.taskunifier.app/app',
    downloadUrl: 'https://www.taskunifier.app/app',
    versionUrl: 'https://api.taskunifier.app/v1/versions/taskunifier-app/latest',
    color: '#0e67c4',
    selectionForegroundColor: '#ffffff',
    selectionBackgroundColor: '#0e67c4',
    fadeIconColor: '#e3ebf2',
    lightIconColor: '#bed5e6',
    disabledColor: '#cccccc',
    defaultObjectColor: '#ffffff',
    processRunningColor: '#20639b',
    processCompletedColor: '#3caea3',
    processErrorColor: '#ed553b',
    conditionTreeGroupAndColor: '#d1f7d9',
    conditionTreeGroupAndActiveColorColor: '#c2e2c9',
    conditionTreeGroupOrColor: '#e8ebf6',
    conditionTreeGroupOrActiveColor: '#d4d7e2',
    conditionTreeGroupNotColor: '#ffc8c5',
    conditionTreeGroupNotActiveColor: '#e3afac',
    archivedColor: '#5e666d',
    defaultTaskTemplateColor: '#ffd632',
    badgeColor: '#0e67c4',
    calendarDateMode_startDate: '#32cd32',
    calendarDateMode_dueDate: '#1e90ff'
};