
import { library } from '@fortawesome/fontawesome-svg-core';
import {
    faArchive,
    faBomb,
    faBoxOpen,
    faBroom,
    faBullseye,
    faCalendarAlt,
    faCaretDown,
    faCheck,
    faCheckDouble,
    faChevronCircleRight,
    faCircle,
    faCog,
    faCogs,
    faCompass,
    faCopy,
    faCubes,
    faDesktop,
    faEdit,
    faExclamationCircle,
    faExclamationTriangle,
    faFilter,
    faFolder,
    faFolderOpen,
    faHome,
    faKey,
    faPaintRoller,
    faPepperHot,
    faPlus,
    faSave,
    faSearch,
    faSpinner,
    faStar,
    faTag,
    faTasks,
    faThumbtack,
    faTimes,
    faTrashAlt
} from '@fortawesome/free-solid-svg-icons';

library.add(faArchive);
library.add(faBomb);
library.add(faBoxOpen);
library.add(faBroom);
library.add(faBullseye);
library.add(faCalendarAlt);
library.add(faCaretDown);
library.add(faCheck);
library.add(faCheckDouble);
library.add(faChevronCircleRight);
library.add(faCircle);
library.add(faCog);
library.add(faCogs);
library.add(faCompass);
library.add(faCopy);
library.add(faCubes);
library.add(faDesktop);
library.add(faEdit);
library.add(faExclamationCircle);
library.add(faExclamationTriangle);
library.add(faFilter);
library.add(faFolder);
library.add(faFolderOpen);
library.add(faHome);
library.add(faKey);
library.add(faPaintRoller);
library.add(faPepperHot);
library.add(faPlus);
library.add(faSave);
library.add(faSearch);
library.add(faSpinner);
library.add(faStar);
library.add(faTag);
library.add(faTasks);
library.add(faThumbtack);
library.add(faTimes);
library.add(faTrashAlt);